/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as P01FeasibilityRouteImport } from './routes/p01-feasibility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const P01FeasibilityRoute = P01FeasibilityRouteImport.update({
  id: '/p01-feasibility',
  path: '/p01-feasibility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p01-feasibility'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p01-feasibility'
  id: '__root__' | '/' | '/p01-feasibility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  P01FeasibilityRoute: typeof P01FeasibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p01-feasibility': {
      id: '/p01-feasibility'
      path: '/p01-feasibility'
      fullPath: '/p01-feasibility'
      preLoaderRoute: typeof P01FeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  P01FeasibilityRoute: P01FeasibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
