/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlignmentStructureRouteImport } from './routes/alignment-structure'
import { Route as ComplexRouteImport } from './routes/complex'
import { Route as HarnessDiagnosticsRouteImport } from './routes/harness-diagnostics'
import { Route as P01FeasibilityRouteImport } from './routes/p01-feasibility'
import { Route as ReferenceViewerRouteImport } from './routes/reference-viewer'
import { Route as RendererPortabilityRouteImport } from './routes/renderer-portability'
import { Route as UniprotStructureRouteImport } from './routes/uniprot-structure'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignmentStructureRoute = AlignmentStructureRouteImport.update({
  id: '/alignment-structure',
  path: '/alignment-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexRoute = ComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessDiagnosticsRoute = HarnessDiagnosticsRouteImport.update({
  id: '/harness-diagnostics',
  path: '/harness-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const P01FeasibilityRoute = P01FeasibilityRouteImport.update({
  id: '/p01-feasibility',
  path: '/p01-feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceViewerRoute = ReferenceViewerRouteImport.update({
  id: '/reference-viewer',
  path: '/reference-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const RendererPortabilityRoute = RendererPortabilityRouteImport.update({
  id: '/renderer-portability',
  path: '/renderer-portability',
  getParentRoute: () => rootRouteImport,
} as any)
const UniprotStructureRoute = UniprotStructureRouteImport.update({
  id: '/uniprot-structure',
  path: '/uniprot-structure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alignment-structure': typeof AlignmentStructureRoute
  '/complex': typeof ComplexRoute
  '/harness-diagnostics': typeof HarnessDiagnosticsRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
  '/reference-viewer': typeof ReferenceViewerRoute
  '/renderer-portability': typeof RendererPortabilityRoute
  '/uniprot-structure': typeof UniprotStructureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alignment-structure': typeof AlignmentStructureRoute
  '/complex': typeof ComplexRoute
  '/harness-diagnostics': typeof HarnessDiagnosticsRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
  '/reference-viewer': typeof ReferenceViewerRoute
  '/renderer-portability': typeof RendererPortabilityRoute
  '/uniprot-structure': typeof UniprotStructureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alignment-structure': typeof AlignmentStructureRoute
  '/complex': typeof ComplexRoute
  '/harness-diagnostics': typeof HarnessDiagnosticsRoute
  '/p01-feasibility': typeof P01FeasibilityRoute
  '/reference-viewer': typeof ReferenceViewerRoute
  '/renderer-portability': typeof RendererPortabilityRoute
  '/uniprot-structure': typeof UniprotStructureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alignment-structure'
    | '/complex'
    | '/harness-diagnostics'
    | '/p01-feasibility'
    | '/reference-viewer'
    | '/renderer-portability'
    | '/uniprot-structure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alignment-structure'
    | '/complex'
    | '/harness-diagnostics'
    | '/p01-feasibility'
    | '/reference-viewer'
    | '/renderer-portability'
    | '/uniprot-structure'
  id:
    | '__root__'
    | '/'
    | '/alignment-structure'
    | '/complex'
    | '/harness-diagnostics'
    | '/p01-feasibility'
    | '/reference-viewer'
    | '/renderer-portability'
    | '/uniprot-structure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignmentStructureRoute: typeof AlignmentStructureRoute
  ComplexRoute: typeof ComplexRoute
  HarnessDiagnosticsRoute: typeof HarnessDiagnosticsRoute
  P01FeasibilityRoute: typeof P01FeasibilityRoute
  ReferenceViewerRoute: typeof ReferenceViewerRoute
  RendererPortabilityRoute: typeof RendererPortabilityRoute
  UniprotStructureRoute: typeof UniprotStructureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alignment-structure': {
      id: '/alignment-structure'
      path: '/alignment-structure'
      fullPath: '/alignment-structure'
      preLoaderRoute: typeof AlignmentStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex': {
      id: '/complex'
      path: '/complex'
      fullPath: '/complex'
      preLoaderRoute: typeof ComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-diagnostics': {
      id: '/harness-diagnostics'
      path: '/harness-diagnostics'
      fullPath: '/harness-diagnostics'
      preLoaderRoute: typeof HarnessDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p01-feasibility': {
      id: '/p01-feasibility'
      path: '/p01-feasibility'
      fullPath: '/p01-feasibility'
      preLoaderRoute: typeof P01FeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-viewer': {
      id: '/reference-viewer'
      path: '/reference-viewer'
      fullPath: '/reference-viewer'
      preLoaderRoute: typeof ReferenceViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renderer-portability': {
      id: '/renderer-portability'
      path: '/renderer-portability'
      fullPath: '/renderer-portability'
      preLoaderRoute: typeof RendererPortabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniprot-structure': {
      id: '/uniprot-structure'
      path: '/uniprot-structure'
      fullPath: '/uniprot-structure'
      preLoaderRoute: typeof UniprotStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignmentStructureRoute: AlignmentStructureRoute,
  ComplexRoute: ComplexRoute,
  HarnessDiagnosticsRoute: HarnessDiagnosticsRoute,
  P01FeasibilityRoute: P01FeasibilityRoute,
  ReferenceViewerRoute: ReferenceViewerRoute,
  RendererPortabilityRoute: RendererPortabilityRoute,
  UniprotStructureRoute: UniprotStructureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
